AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 2.7.0
Layout/ParameterAlignment:
  Enabled: false
Metrics/AbcSize:
  Max: 25
Style/AndOr:
  EnforcedStyle: conditionals
Style/TrailingCommaInArrayLiteral:
  Enabled: false
Style/TrailingCommaInHashLiteral:
  Enabled: false
Style/NumericPredicate:
  Enabled: false
Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true
