AllCops:
  TargetRubyVersion: 2.5.0
Layout/ParameterAlignment:
  Enabled: false
Metrics/AbcSize:
  Max: 25
Style/AndOr:
  EnforcedStyle: conditionals
Style/TrailingCommaInArrayLiteral:
  Enabled: false
Style/TrailingCommaInHashLiteral:
  Enabled: false
Style/NumericPredicate:
  Enabled: false
