AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 2.7.0
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma
